### ISSUE TITLE
It isn't catching the balls

### ISSUE THREAD

**Issue by tollari** [ballsdex-autocatcher/ballsdex-autocatcher#5] opened 2024-01-21 19:00 UTC
I have done everything correctly. and it even shows **USERNAME is ready** in console.

But whenever the ball spawns, it doesn't catch it. Neither it detects that a ball has spawned. 
There's no DOWNLOAD IMAGE message in console.

**Comment by M-logique** [comment] 2024-01-21 20:44
I know your problem
Ballsdex team is sniffing our code and they patched our detection methods by adding some black and white things In the corner of the spawn art. So the source can't catch balls anymore for now. But it's not insolvable and we have plans for it. We just looking for some encryption methods that Obfuscate our code to prevent patchs.
Please Be patient. If you decide to receive a message from us when the problem is solved, reply to this message with an email address or send a message to my email.

```
logique@duck.com
```

**Comment by M-logique** [comment] 2024-01-21 20:51
And I forgot to comment this
The code currently does not download the image for further optimization.  It just encodes bytes using base64 and compares with all spawn art.

**Comment by tollari** [comment] 2024-01-22 13:48
> I know your problem Ballsdex team is sniffing our code and they patched our detection methods by adding some black and white things In the corner of the spawn art. So the source can't catch balls anymore for now. But it's not insolvable and we have plans for it. We just looking for some encryption methods that Obfuscate our code to prevent patchs. Please Be patient. If you decide to receive a message from us when the problem is solved, reply to this message with an email address or send a message to my email.
> 
> ```
> logique@duck.com
> ```

alright. sure, i would like to know when it's resolved.

**Comment by xplanthris** [comment] 2024-01-22 16:31
> I know your problem Ballsdex team is sniffing our code and they patched our detection methods by adding some black and white things In the corner of the spawn art. So the source can't catch balls anymore for now. But it's not insolvable and we have plans for it. We just looking for some encryption methods that Obfuscate our code to prevent patchs. Please Be patient. If you decide to receive a message from us when the problem is solved, reply to this message with an email address or send a message to my email.
> 
> ```
> logique@duck.com
> ```

Your making the code open source problem is so really you would have to make it closed source and obfuscated

**Comment by mohammad87115** [comment] 2024-01-22 16:50
😔

**Comment by M-logique** [comment] 2024-01-22 18:36
> > I know your problem Ballsdex team is sniffing our code and they patched our detection methods by adding some black and white things In the corner of the spawn art. So the source can't catch balls anymore for now. But it's not insolvable and we have plans for it. We just looking for some encryption methods that Obfuscate our code to prevent patchs. Please Be patient. If you decide to receive a message from us when the problem is solved, reply to this message with an email address or send a message to my email.
> > ```
> > logique@duck.com
> > ```
> 
> Your making the code open source problem is so really you would have to make it closed source and obfuscated

The code was closed source but but no one wanted to buy it, and when ballsdex listed me and my friend, We decided to make it public.

**Comment by mohammad87115** [comment] 2024-01-25 10:05
@xplanthris @tollari It sounds like Ballsdex decided to remove the rectangles in the spawn image.
the problem is **fixed** and the code is now **working**

**Comment by M-logique** [comment] 2024-01-25 11:19
> @xplanthris @tollari It sounds like Ballsdex decided to remove the rectangles in the spawn image. the problem is **fixed** and the code is now **working**

No
Go update the code fat ass

**Comment by tollari** [comment] 2024-01-26 11:35
also, how do you get all the images of balls? they keep updating. so, is there a way to get the latest images of balls?

**Comment by M-logique** [comment] 2024-01-26 11:50
> also, how do you get all the images of balls? they keep updating. so, is there a way to get the latest images of balls?

For the first time, Mohammad (author) created a scrapping tool that fetched all of the balls who spawned in ballsdex server's spawn channel
And for now, I manually update spawn arts.

**Comment by M-logique** [comment] 2024-01-26 11:51
> @xplanthris @tollari It sounds like Ballsdex decided to remove the rectangles in the spawn image. the problem is **fixed** and the code is now **working**

Its not working
I publish the alpha version for now

**Comment by M-logique** [comment] 2024-01-26 12:43
@xplanthris & @tollari , I committed the new changes and the code now works perfectly.
update your codes.

**Comment by tollari** [comment] 2024-01-26 22:14
alr. thanks. let me check

**Closed** 2024-08-12 12:26 UTC
